export const MovieData = {
    page: 1,
    results: [
        {
            adult: true,
            backdrop_path: "/fY3lD0jM5AoHJMunjGWqJ0hRteI.jpg",
            genre_ids: [878, 27, 28],
            id: 940721,
            original_language: "ja",
            original_title: "ゴジラ-1.0",
            overview:
                "Postwar Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.",
            popularity: 2735.613,
            poster_path: "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
            release_date: "2023-11-03",
            title: "Godzilla Minus One",
            video: false,
            vote_average: 7.726,
            vote_count: 883,
        },
        {
            adult: false,
            backdrop_path: "/iHYh4cdO8ylA3W0dUxTDVdyJ5G9.jpg",
            genre_ids: [878, 12, 28],
            id: 653346,
            original_language: "en",
            original_title: "Kingdom of the Planet of the Apes",
            overview:
                "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
            popularity: 2138.511,
            poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
            release_date: "2024-05-08",
            title: "Kingdom of the Planet of the Apes",
            video: false,
            vote_average: 7.099,
            vote_count: 141,
        },
        {
            adult: false,
            backdrop_path: "/sI6uCeF8mUlZx22mFfHSi9W3XQ9.jpg",
            genre_ids: [10749, 35],
            id: 843527,
            original_language: "en",
            original_title: "The Idea of You",
            overview:
                "40-year-old single mom Solène begins an unexpected romance with 24-year-old Hayes Campbell, the lead singer of August Moon, the hottest boy band on the planet.",
            popularity: 1380.647,
            poster_path: "/zDi2U7WYkdIoGYHcYbM9X5yReVD.jpg",
            release_date: "2024-05-02",
            title: "The Idea of You",
            video: false,
            vote_average: 7.548,
            vote_count: 557,
        },
        {
            adult: false,
            backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
            genre_ids: [28, 878, 12],
            id: 823464,
            original_language: "en",
            original_title: "Godzilla x Kong: The New Empire",
            overview:
                "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
            popularity: 1416.188,
            poster_path: "/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
            release_date: "2024-03-27",
            title: "Godzilla x Kong: The New Empire",
            video: false,
            vote_average: 6.483,
            vote_count: 1022,
        },
        {
            adult: false,
            backdrop_path: "/5cCfqeUH2f5Gnu7Lh9xepY9TB6x.jpg",
            genre_ids: [14, 12, 35],
            id: 967847,
            original_language: "en",
            original_title: "Ghostbusters: Frozen Empire",
            overview:
                "The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who've developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
            popularity: 1286.608,
            poster_path: "/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg",
            release_date: "2024-03-20",
            title: "Ghostbusters: Frozen Empire",
            video: false,
            vote_average: 6.651,
            vote_count: 548,
        },
        {
            adult: false,
            backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
            genre_ids: [878, 12],
            id: 693134,
            original_language: "en",
            original_title: "Dune: Part Two",
            overview:
                "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
            popularity: 1180.453,
            poster_path: "/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg",
            release_date: "2024-02-27",
            title: "Dune: Part Two",
            video: false,
            vote_average: 8.214,
            vote_count: 3770,
        },
        {
            adult: false,
            backdrop_path: "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
            genre_ids: [27, 53, 35],
            id: 1111873,
            original_language: "en",
            original_title: "Abigail",
            overview:
                "After a group of would-be criminals kidnap the 12 year old ballerina daughter of a powerful underworld figure, all they have to do to collect a $50 million ransom is watch the girl overnight. In an isolated mansion, the captors start to dwindle, one by one, and they discover, to their mounting horror, that they’re locked inside with no normal little girl.",
            popularity: 1161.831,
            poster_path: "/5Uq8P6MPj9Ppsns5t82AiCiUaWE.jpg",
            release_date: "2024-04-18",
            title: "Abigail",
            video: false,
            vote_average: 7.2,
            vote_count: 235,
        },
        {
            adult: false,
            backdrop_path: "/kYgQzzjNis5jJalYtIHgrom0gOx.jpg",
            genre_ids: [16, 28, 10751, 35, 14],
            id: 1011985,
            original_language: "en",
            original_title: "Kung Fu Panda 4",
            overview:
                "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
            popularity: 1057.94,
            poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
            release_date: "2024-03-02",
            title: "Kung Fu Panda 4",
            video: false,
            vote_average: 7.1,
            vote_count: 1570,
        },
        {
            adult: false,
            backdrop_path: "/7kQvHmGyKJv2wSKVfCUux50rd7A.jpg",
            genre_ids: [878],
            id: 920342,
            original_language: "zh",
            original_title: "异兽战场",
            overview:
                "The soldier king Qin Yang's fiancée Ye Qin met with an unknown beast and died tragically. Gu Ping invites him to participate in Ye Qin's scientific research before her death. But Gu Ping is using Ye Qin's research results to combine the genes of unknown beasts to create the \"Zero\" dragon creature. The intelligent dragon creature, coupled with the extra-terrestrial beast evolved by devouring,  an imminent city war is coming...",
            popularity: 986.074,
            poster_path: "/nBVYp2xxx2R02n21EGlDky8CgWR.jpg",
            release_date: "2021-12-27",
            title: "Monster's Battlefield",
            video: false,
            vote_average: 5.75,
            vote_count: 2,
        },
        {
            adult: false,
            backdrop_path: "/jnE1GA7cGEfv5DJBoU2t4bZHaP4.jpg",
            genre_ids: [28, 878],
            id: 1094844,
            original_language: "en",
            original_title: "Ape vs. Mecha Ape",
            overview:
                "Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.",
            popularity: 1005.236,
            poster_path: "/dJaIw8OgACelojyV6YuVsOhtTLO.jpg",
            release_date: "2023-03-24",
            title: "Ape vs. Mecha Ape",
            video: false,
            vote_average: 5.331,
            vote_count: 145,
        },
        {
            adult: false,
            backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
            genre_ids: [28, 27, 53],
            id: 1096197,
            original_language: "en",
            original_title: "No Way Up",
            overview:
                "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
            popularity: 889.2,
            poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
            release_date: "2024-01-18",
            title: "No Way Up",
            video: false,
            vote_average: 6.417,
            vote_count: 618,
        },
        {
            adult: false,
            backdrop_path: "/tpiqEVTLRz2Mq7eLq5DT8jSrp71.jpg",
            genre_ids: [878, 28, 18],
            id: 934632,
            original_language: "en",
            original_title: "Rebel Moon - Part Two: The Scargiver",
            overview:
                "The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
            popularity: 755.974,
            poster_path: "/cxevDYdeFkiixRShbObdwAHBZry.jpg",
            release_date: "2024-04-19",
            title: "Rebel Moon - Part Two: The Scargiver",
            video: false,
            vote_average: 6.122,
            vote_count: 696,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [18, 10770],
            id: 1219685,
            original_language: "fr",
            original_title: "Un père idéal",
            overview: "",
            popularity: 1050.787,
            poster_path: "/4xJd3uwtL1vCuZgEfEc8JXI9Uyx.jpg",
            release_date: "2024-04-21",
            title: "Un père idéal",
            video: false,
            vote_average: 0,
            vote_count: 0,
        },
        {
            adult: false,
            backdrop_path: "/x1Ex090BNIXcmaBYB2US0j3hBUF.jpg",
            genre_ids: [28, 53, 18],
            id: 1057001,
            original_language: "ko",
            original_title: "The Childe",
            overview:
                "Desperate to secure funds for his mother's surgery, an amateur boxer searches for the wealthy father he's never met. Traveling from the Philippines to Korea, he is relentlessly pursued and forced to confront a shocking truth.",
            popularity: 732.642,
            poster_path: "/ydC8ubFXQfkPJDhkduMhbE9mTz7.jpg",
            release_date: "2023-06-21",
            title: "The Childe",
            video: false,
            vote_average: 7,
            vote_count: 73,
        },
        {
            adult: false,
            backdrop_path: "/v5XyXZe8FADw8iHupB4L7QOAwH9.jpg",
            genre_ids: [16, 35, 10751],
            id: 748783,
            original_language: "en",
            original_title: "The Garfield Movie",
            overview:
                "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
            popularity: 671.405,
            poster_path: "/zK2sFxZcelHJRPVr242rxy5VK4T.jpg",
            release_date: "2024-04-30",
            title: "The Garfield Movie",
            video: false,
            vote_average: 6.5,
            vote_count: 52,
        },
        {
            adult: false,
            backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
            genre_ids: [28, 12, 53, 80],
            id: 7451,
            original_language: "en",
            original_title: "xXx",
            overview:
                'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
            popularity: 653.902,
            poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
            release_date: "2002-08-09",
            title: "xXx",
            video: false,
            vote_average: 5.931,
            vote_count: 4036,
        },
        {
            adult: false,
            backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
            genre_ids: [18, 36],
            id: 872585,
            original_language: "en",
            original_title: "Oppenheimer",
            overview:
                "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
            popularity: 595.42,
            poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
            release_date: "2023-07-19",
            title: "Oppenheimer",
            video: false,
            vote_average: 8.1,
            vote_count: 7960,
        },
        {
            adult: false,
            backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
            genre_ids: [27, 9648, 53],
            id: 1041613,
            original_language: "en",
            original_title: "Immaculate",
            overview:
                "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
            popularity: 566.421,
            poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
            release_date: "2024-03-20",
            title: "Immaculate",
            video: false,
            vote_average: 6.158,
            vote_count: 424,
        },
        {
            adult: false,
            backdrop_path: "/AuTfo1lbE8s2Y8RVTmlbJAeLWPK.jpg",
            genre_ids: [28, 53],
            id: 850888,
            original_language: "es",
            original_title: "Sayen: La cazadora",
            overview:
                "Realizing that she cannot take down Fisk alone, Sayen teams up with an underground resistance group with a plan to expose and end Fisk's unchecked plundering once and for all.",
            popularity: 531.554,
            poster_path: "/upKD8UbH8vQ798aMWgwMxV8t4yk.jpg",
            release_date: "2024-04-26",
            title: "Sayen: The Huntress",
            video: false,
            vote_average: 6.4,
            vote_count: 24,
        },
        {
            adult: false,
            backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
            genre_ids: [878, 12],
            id: 438631,
            original_language: "en",
            original_title: "Dune",
            overview:
                "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
            popularity: 550.083,
            poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
            release_date: "2021-09-15",
            title: "Dune",
            video: false,
            vote_average: 7.779,
            vote_count: 11560,
        },
    ],
    total_pages: 44100,
    total_results: 881996,
};
